from django.db import migrations
from django.contrib.auth.hashers import make_password

# list of 100+ default users
SEED_USERS = [
    ("alice", "alice1"),
    ("bob", "bob2"),
    ("charlie", "charlie3"),
    ("david", "david4"),
    ("eve", "eve5"),
    ("frank", "frank6"),
    ("grace", "grace7"),
    ("heidi", "heidi8"),
    ("ivan", "ivan9"),
    ("judy", "judy10"),
    ("mallory", "mallory11"),
    ("niaj", "niaj12"),
    ("oscar", "oscar13"),
    ("peggy", "peggy14"),
    ("quinn", "quinn15"),
    ("rupert", "rupert16"),
    ("sybil", "sybil17"),
    ("trent", "trent18"),
    ("ursula", "ursula19"),
    ("victor", "victor20"),
    ("wendy", "wendy21"),
    ("xander", "xander22"),
    ("yvonne", "yvonne23"),
    ("zack", "zack24"),
    ("alpha", "alpha25"),
    ("realname", "realname26"),
    ("emily", "emily27"),
    ("oliver", "oliver28"),
    ("sophia", "sophia29"),
    ("liam", "liam30"),         
    ("ava", "ava31"),
    ("noah", "noah32"),
    ("isabella", "isabella33"),
    ("elijah", "elijah34"),
    ("mia", "mia35"),
    ("james", "james36"),
    ("charlotte", "charlotte37"),
    ("benjamin", "benjamin38"),
    ("amelia", "amelia39"),
    ("lucas", "lucas40"),
    ("harper", "harper41"),
    ("mason", "mason42"),
    ("evelyn", "evelyn43"),
    ("ethan", "ethan44"),
    ("abigail", "abigail45"),
    ("alexander", "alexander46"),
    ("ella", "ella47"),
    ("henry", "henry48"),
    ("scarlett", "scarlett49"),
    ("jacob", "jacob50"),
    ("grace", "grace51"),
    ("michael", "michael52"),
    ("chloe", "chloe53"),
    ("daniel", "daniel54"),
    ("victoria", "victoria55"),
    ("logan", "logan56"),
    ("riley", "riley57"),
    ("jack", "jack58"),
    ("ariana", "ariana59"),
    ("sebastian", "sebastian60"),
    ("nora", "nora61"),
    ("aiden", "aiden62"),
    ("zoey", "zoey63"),
    ("owen", "owen64"),
    ("lily", "lily65"),
    ("samuel", "samuel66"),
    ("hannah", "hannah67"),
    ("gabriel", "gabriel68"),
    ("layla", "layla69"),
    ("carter", "carter70"),
    ("lillian", "lillian71"),
    ("jayden", "jayden72"),
    ("addison", "addison73"),
    ("lucy", "lucy74"),
    ("dylan", "dylan75"),
    ("aubrey", "aubrey76"),
    ("levi", "levi77"),
    ("zoe", "zoe78"),
    ("isaac", "isaac79"),
    ("stella", "stella80"),
    ("julian", "julian81"),
    ("natalie", "natalie82"),
    ("david", "david83"),
    ("hazel", "hazel84"),
    ("caleb", "caleb85"),
    ("violet", "violet86"),
    ("ryan", "ryan87"),
    ("aurora", "aurora88"),
    ("joseph", "joseph89"),
    ("savannah", "savannah90"),
    ("nathan", "nathan91"),
    ("brooklyn", "brooklyn92"),
    ("leo", "leo93"),
    ("bella", "bella94"),
    ("adam", "adam95"),
    ("claire", "claire96"),
    ("christian", "christian97"),
    ("skylar", "skylar98"),
    ("hunter", "hunter99"),
    ("paisley", "paisley100"),
    ("ezra", "ezra101"),
    ("everly", "everly102"),
    ("jonathan", "jonathan103"),
    ("anna", "anna104"),
    ("thomas", "thomas105"),
    ("caroline", "caroline106"),
    ("charles", "charles107"),
    ("nova", "nova108"),
    ("joshua", "joshua109"),
    ("genesis", "genesis110"),
]

def seed_named_users(apps, schema_editor):
    SimpleUser = apps.get_model("planner", "SimpleUser")
    for username, raw_password in SEED_USERS:
        SimpleUser.objects.update_or_create(
            userName=username,
            defaults={"password": make_password(raw_password)},
        )

def unseed_named_users(apps, schema_editor):
    SimpleUser = apps.get_model("planner", "SimpleUser")
    usernames = [u for u, _ in SEED_USERS]
    SimpleUser.objects.filter(userName__in=usernames).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('planner', '0001_initial'),
        ('planner', '0002_route')
    ]

    operations = [
        migrations.RunPython(seed_named_users, reverse_code=unseed_named_users),
    ]