# Generated by Django 5.2.7 on 2025-11-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_route"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SimpleUser",
        ),
    ]
