# Generated by Django 5.2.7 on 2025-12-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_delete_simpleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
