# Generated by Django 5.2.7 on 2025-12-02 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_seed_more_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_ids', models.JSONField()),
                ('route_ids', models.JSONField()),
                ('route_names', models.JSONField()),
                ('distance_meters', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.simpleuser')),
            ],
        ),
    ]
